apiVersion: v1
kind: Service
metadata:
  name: climapp-backend-service
spec:
  selector:
    app: climapp-backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: climapp-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: climapp-frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: climapp-db-service
spec:
  selector:
    app: climapp-db
  ports:
  - port: 5432
    targetPort: 5432